### ISSUE TITLE
Data to NINA is sent re-bayered from a debayered state

### ISSUE THREAD

**Issue by rootdarkarchon** [Axlns/ascom.dslr.sony#1]
Hello,

I am a contributor for NINA and I am looking into this driver for a few people that would like to use this but I found a weird quirk especially for usage in NINA (technically also usage in general imo). The driver is debayering the data it receives from the camera and for software that doesn't support multi-plane-images it tries to bayer it again. VNG is a lossy algorithm for debayering data and you cannot restore the bayered data from it again. That does make the driver a bit useless for the usage in NINA.
Would it be possible that you modify it so it sends actual raw monochrome data to NINA without going the process of debayering it first?

Generally it is assumed that ASCOM drivers provide raw camera data as it comes from the camera. Modification, like debayering, is unexpected behavior.

Kind regards,
Stanley

**Comment by Axlns** [comment]
Hello. This driver uses C++ library called LibRaw (https://www.libraw.org/) to work with Sony ARW files and extract image data. When image format is set to CFA in driver settings (should be default value), driver uses LibRaw to extract raw bayered monochrome data from ARW file. It does not do debayering and then bayering - it just reads ARW file and returns unmodified image array data. The driver will do debayering if you set image format to "Debayered".

**Comment by rootdarkarchon** [comment]
Oh man I might have had a huge brainfart here and confused this with another ASCOM Sony camera driver. There are just too many - another one did exactly this as described. My bad, have a nice day.
